-- EMOTES QUEST DK
-- By Duende
UPDATE quest_template SET DetailsEmote1 = '22', DetailsEmote2 = '500', DetailsEmote3 = '100', DetailsEmote4 = '1000', OfferRewardEmote1 = '1', OfferRewardEmote2 = '5', OfferRewardEmote3 = '1', OfferRewardEmote4 = '25' WHERE entry = '12593';
UPDATE quest_template SET DetailsEmote1 = '25', CompleteEmote = '5', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '6' WHERE entry = '12619';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '25', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1' WHERE entry = '12842';
UPDATE quest_template SET DetailsEmote1 = '4' WHERE entry = '12848';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '396', OfferRewardEmote2 = '396', OfferRewardEmote3 = '396' WHERE entry = '12636';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '396', OfferRewardEmote2 = '396', OfferRewardEmote3 = '396' WHERE entry = '12641';
UPDATE quest_template SET DetailsEmote1 = '22', DetailsEmoteDelay2 = '1000', DetailsEmoteDelay3 = '2000', DetailsEmoteDelay4 = '2000' , OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '6' WHERE entry = '12657';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '5', OfferRewardEmote2 = '1', OfferRewardEmote3 = '66' WHERE entry = '12850';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '6', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1' WHERE entry = '12670';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '6', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1' WHERE entry = '12678';
UPDATE quest_template SET DetailsEmote1 = '22', OfferRewardEmote1 = '15', OfferRewardEmote2 = '6', OfferRewardEmote3 = '274', OfferRewardEmote4 = '1' WHERE entry = '12697';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '15' WHERE entry = '12698';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '4' WHERE entry = '12700';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '11', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '5' WHERE entry = '12701';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '5', OfferRewardEmote4 = '274' WHERE entry = '12706';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '5', OfferRewardEmote2 = '1', OfferRewardEmote3 = '4' WHERE entry = '12714';UPDATE quest_template SET DetailsEmote1 = '25', OfferRewardEmote1 = '2', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '6' WHERE entry = '12715';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '5', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '5' WHERE entry = '12719';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '6', OfferRewardEmote2 = '5', OfferRewardEmote3 = '1', OfferRewardEmote4 = '273' WHERE entry = '12720';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1' WHERE entry = '12723';
UPDATE quest_template SET DetailsEmote1 = '22', CompleteEmote = '5', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '5' WHERE entry = '12724';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '5', OfferRewardEmote1 = '1', OfferRewardEmote2 = '11', OfferRewardEmote3 = '1' WHERE entry = '12754';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '6', OfferRewardEmote1 = '5', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1' WHERE entry = '12755';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '11', OfferRewardEmote1 = '1', OfferRewardEmote2 = '5', OfferRewardEmote3 = '1' WHERE entry = '12756';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '6', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '15' WHERE entry = '12757';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '6' WHERE entry = '12716';
UPDATE quest_template SET DetailsEmote1 = '4' WHERE entry = '12717';
UPDATE quest_template SET DetailsEmote1 = '25' WHERE entry = '12725';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '6', OfferRewardEmote1 = '15', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '1' WHERE entry = '12727';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1' WHERE entry = '12738';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '4', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1' WHERE entry = '12751';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '396', OfferRewardEmote2 = '396', OfferRewardEmote3 = '25' WHERE entry = '12778';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '397', OfferRewardEmote2 = '396', OfferRewardEmote3 = '396' WHERE entry = '12779';
UPDATE quest_template SET DetailsEmote1 = '22', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1' WHERE entry = '12800';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '25' WHERE entry = '12801';
UPDATE quest_template SET DetailsEmote1 = '25', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1' WHERE entry = '13165';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '25' WHERE entry = '13166';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '25', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '15', OfferRewardEmote4 = '25' WHERE entry = '13188';
UPDATE quest_template SET DetailsEmote1 = '4', CompleteEmote = '25', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '15', OfferRewardEmote4 = '25' WHERE entry = '13189';
UPDATE quest_template SET DetailsEmote1 = '66', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1' WHERE entry = '12733';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '6' WHERE entry = '12680';
UPDATE quest_template SET DetailsEmote1 = '4', OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '2' WHERE entry = '12687';
UPDATE quest_template SET DetailsEmote1 = '22' WHERE entry = '12722';
UPDATE quest_template SET OfferRewardEmote1 = '1', OfferRewardEmote2 = '1', OfferRewardEmote3 = '1', OfferRewardEmote4 = '5' WHERE entry = '12849';
UPDATE quest_template SET DetailsEmote1 = '21', CompleteEmote = '1', OfferRewardEmote1 = '1', OfferRewardEmote2 = '2' WHERE entry = '12679';
UPDATE quest_template SET DetailsEmote1 = '66', CompleteEmote = '1' WHERE entry = '2281';
UPDATE quest_template SET CompleteEmote = '1' WHERE entry = '2282';
UPDATE quest_template SET CompleteEmote = '1' WHERE entry = '2241';
UPDATE quest_template SET CompleteEmote = '1' WHERE entry = '2241'; 