-- access_requirement comments  
-- By Madalex

Update `access_requirement` SET `comment`='Scarlet Monastery - Graveyard (Entrance)' WHERE `id`='45';
Update `access_requirement` SET `comment`='DeadMines Entrance' WHERE `id`='78';
Update `access_requirement` SET `comment`='Stormwind Stockades Entrance' WHERE `id`='101';
Update `access_requirement` SET `comment`='Stormwind Vault Entrance' WHERE `id`='107';
Update `access_requirement` SET `comment`='Stormwind Vault Instance' WHERE `id`='109';
Update `access_requirement` SET `comment`='DeadMines Instance Start' WHERE `id`='119';
Update `access_requirement` SET `comment`='Deadmines Instance End' WHERE `id`='121';
Update `access_requirement` SET `comment`='Shadowfang Keep Entrance' WHERE `id`='145';
Update `access_requirement` SET `comment`='Shadowfang keep - Entrance' WHERE `id`='194';
Update `access_requirement` SET `comment`='The Barrens - Wailing Caverns' WHERE `id`='226';
Update `access_requirement` SET `comment`='The Barrens - Wailing Caverns' WHERE `id`='228';
Update `access_requirement` SET `comment`='Razorfen Kraul Instance Start' WHERE `id`='242';
Update `access_requirement` SET `comment`='Razorfen Kraul Entrance' WHERE `id`='244';
Update `access_requirement` SET `comment`='Blackphantom Deeps Entrance' WHERE `id`='257';
Update `access_requirement` SET `comment`='Blackphantom Deeps Instance Start' WHERE `id`='259';
Update `access_requirement` SET `comment`='Uldaman Entrance' WHERE `id`='286';
Update `access_requirement` SET `comment`='Uldaman Instance Start' WHERE `id`='288';
Update `access_requirement` SET `comment`='Gnomeregan Instance Start' WHERE `id`='322';
Update `access_requirement` SET `comment`='Gnomeregan Entrance' WHERE `id`='324';
Update `access_requirement` SET `comment`='Razorfen Downs Entrance' WHERE `id`='442';
Update `access_requirement` SET `comment`='Razorfen Downs Instance Start' WHERE `id`='444';
Update `access_requirement` SET `comment`='Altar of Atal\Hakkar Entrance' WHERE `id`='446';
Update `access_requirement` SET `comment`='Altar Of Atal\Hakkar Instance Start' WHERE `id`='448';
Update `access_requirement` SET `comment`='Stockades Instance' WHERE `id`='503';
Update `access_requirement` SET `comment`='Gnomeregan Train Depot Entrance' WHERE `id`='523';
Update `access_requirement` SET `comment`='Gnomeregan Train Depot Instance' WHERE `id`='525';
Update `access_requirement` SET `comment`='Teddrassil - Ruth Theran' WHERE `id`='527';
Update `access_requirement` SET `comment`='Teddrassil - Darnassus' WHERE `id`='542';
Update `access_requirement` SET `comment`='Scarlet Monastery - Graveyard (Exit)' WHERE `id`='602';
Update `access_requirement` SET `comment`='Scarlet Monastery - Cathedral (Exit)' WHERE `id`='604';
Update `access_requirement` SET `comment`='Scarlet Monastery - Armory (Exit)' WHERE `id`='606';
Update `access_requirement` SET `comment`='Scarlet Monastery - Library (Exit)' WHERE `id`='608';
Update `access_requirement` SET `comment`='Scarlet Monastery - Cathedral (Entrance)' WHERE `id`='610';
Update `access_requirement` SET `comment`='Scarlet Monastery - Armory (Entrance)' WHERE `id`='612';
Update `access_requirement` SET `comment`='Scarlet Monastery - Library (Entrance)' WHERE `id`='614';
Update `access_requirement` SET `comment`='Stormwind - Wizard Sanctum Room' WHERE `id`='702';
Update `access_requirement` SET `comment`='Stormwind - Wizard Sanctum Tower Portal' WHERE `id`='704';
Update `access_requirement` SET `comment`='Uldaman Instance End' WHERE `id`='882';
Update `access_requirement` SET `comment`='Uldaman Exit' WHERE `id`='902';
Update `access_requirement` SET `comment`='Zul\Farrak Instance Start' WHERE `id`='922';
Update `access_requirement` SET `comment`='Zul\Farrak Entrance' WHERE `id`='924';
Update `access_requirement` SET `comment`='Onyxia\s Lair - Dustwallow Instance' WHERE `id`='1064';
Update `access_requirement` SET `comment`='Blackrock Mountain - Searing Gorge Instance?' WHERE `id`='1466';
Update `access_requirement` SET `comment`='Blackrock Spire - Searing Gorge Instance (Inside)' WHERE `id`='1468';
Update `access_requirement` SET `comment`='Blackrock Spire - Searing Gorge Instance' WHERE `id`='1470';
Update `access_requirement` SET `comment`='Blackrock Dephts - Searing Gorge Instance' WHERE `id`='1472';
Update `access_requirement` SET `comment`='Deeprun Tram - Ironforge Instance (Inside)' WHERE `id`='2166';
Update `access_requirement` SET `comment`='Deeprun Tram - Stormwind Instance (Inside)' WHERE `id`='2171';
Update `access_requirement` SET `comment`='Deeprun Tram - Stormwind Instance' WHERE `id`='2173';
Update `access_requirement` SET `comment`='Deeprun Tram - Ironforge Instance' WHERE `id`='2175';
Update `access_requirement` SET `comment`='Stratholme - Eastern Plaguelands Instance' WHERE `id`='2214';
Update `access_requirement` SET `comment`='Stratholme - Eastern Plaguelands Instance' WHERE `id`='2216';
Update `access_requirement` SET `comment`='Stratholme - Eastern Plaguelands Instance' WHERE `id`='2217';
Update `access_requirement` SET `comment`='Stratholme - Eastern Plaguelands Instance (Inside)' WHERE `id`='2221';
Update `access_requirement` SET `comment`='Ragefire Chasm - Ogrimmar Instance (Inside)' WHERE `id`='2226';
Update `access_requirement` SET `comment`='Ragefire Chasm - Ogrimmar Instance' WHERE `id`='2230';
Update `access_requirement` SET `comment`='Utgarde Keep (exit)' WHERE `id`='4743';
Update `access_requirement` SET `comment`='Hall of Legends - Ogrimmar (Inside)' WHERE `id`='2530';
Update `access_requirement` SET `comment`='Stormwind (Inside) - Champions Hall' WHERE `id`='2534';
Update `access_requirement` SET `comment`='Scholomance Entrance' WHERE `id`='2567';
Update `access_requirement` SET `comment`='Scholomance Instance' WHERE `id`='2568';
Update `access_requirement` SET `comment`='Alterac Valley - Horde Exit' WHERE `id`='2606';
Update `access_requirement` SET `comment`='Alterac Valley - Alliance Exit' WHERE `id`='2608';
Update `access_requirement` SET `comment`='Onyxia\s Lair Entrance' WHERE `id`='2848';
Update `access_requirement` SET `comment`='The Molten Bridge' WHERE `id`='2886';
Update `access_requirement` SET `comment`='Molten Core Entrance, Inside' WHERE `id`='2890';
Update `access_requirement` SET `comment`='Maraudon' WHERE `id`='3126';
Update `access_requirement` SET `comment`='Maraudon' WHERE `id`='3131';
Update `access_requirement` SET `comment`='Maraudon' WHERE `id`='3133';
Update `access_requirement` SET `comment`='Maraudon' WHERE `id`='3134';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3183';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3184';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3185';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3186';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3187';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3189';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3190';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3191';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3193';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3194';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3195';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3196';
Update `access_requirement` SET `comment`='Dire Maul' WHERE `id`='3197';
Update `access_requirement` SET `comment`='The Molten Core Window(Lava) Entrance' WHERE `id`='3529';
Update `access_requirement` SET `comment`='Blackwing Lair - Blackrock Mountain - Eastern Kingdoms' WHERE `id`='3726';
Update `access_requirement` SET `comment`='Blackrock Spire, Unknown' WHERE `id`='3728';
Update `access_requirement` SET `comment`='Zul\Gurub Entrance ' WHERE `id`='3928';
Update `access_requirement` SET `comment`='Zul\Gurub Exit' WHERE `id`='3930';
Update `access_requirement` SET `comment`='Arathi Basin Alliance Out' WHERE `id`='3948';
Update `access_requirement` SET `comment`='Arathi Basin Horde Out' WHERE `id`='3949';
Update `access_requirement` SET `comment`='The Molten Core Window Entrance' WHERE `id`='3528';
Update `access_requirement` SET `comment`='Ruins Of Ahn\Qiraj (Inside)' WHERE `id`='4006';
Update `access_requirement` SET `comment`='Ruins Of Ahn\Qiraj (Outside)' WHERE `id`='4008';
Update `access_requirement` SET `comment`='Ahn\Qiraj Temple (Outside)' WHERE `id`='4010';
Update `access_requirement` SET `comment`='Ahn\Qiraj Temple (Inside)' WHERE `id`='4012';
Update `access_requirement` SET `comment`='Utgarde Keep (entrance)' WHERE `id`='4745';
Update `access_requirement` SET `comment`='Karazhan, Main (Entrance)' WHERE `id`='4131';
Update `access_requirement` SET `comment`='The Shattered Halls (Exit)' WHERE `id`='4145';
Update `access_requirement` SET `comment`='The Blood Furnace (Exit)' WHERE `id`='4147';
Update `access_requirement` SET `comment`='Magtheridon\s Lair (Exit)' WHERE `id`='4149';
Update `access_requirement` SET `comment`='Hellfire Ramparts (Entrance)' WHERE `id`='4150';
Update `access_requirement` SET `comment`='The Shattered Halls (Entrance)' WHERE `id`='4151';
Update `access_requirement` SET `comment`='The Blood Furnace (Entrance)' WHERE `id`='4152';
Update `access_requirement` SET `comment`='Magtheridon\s Lair (Entrance)' WHERE `id`='4153';
Update `access_requirement` SET `comment`='Naxxramas (to frostwyrm lair)' WHERE `id`='4156';
Update `access_requirement` SET `comment`='Hellfire Ramparts (Exit)' WHERE `id`='4297';
Update `access_requirement` SET `comment`='Battle Of Mount Hyjal, Alliance Base (Entrance)' WHERE `id`='4311';
Update `access_requirement` SET `comment`='Battle Of Mount Hyjal, Horde Base (Entrance)' WHERE `id`='4312';
Update `access_requirement` SET `comment`='Battle Of Mount Hyjal, Night Elf Base (Entrance)' WHERE `id`='4313';
Update `access_requirement` SET `comment`='Caverns Of Time, Battle Of Mount Hyjal (Entrance) ' WHERE `id`='4319';
Update `access_requirement` SET `comment`='Caverns Of Time, Black Morass (Entrance)' WHERE `id`='4320';
Update `access_requirement` SET `comment`='Caverns Of Time, Old Hillsbrad Foothills (Entrance)' WHERE `id`='4321';
Update `access_requirement` SET `comment`='Caverns Of Time, Black Morass (Exit)' WHERE `id`='4322';
Update `access_requirement` SET `comment`='Caverns Of Time, Battle Of Mount Hyjal (Exit)' WHERE `id`='4323';
Update `access_requirement` SET `comment`='Caverns Of Time, Old Hillsbrad Foothills (Exit)' WHERE `id`='4324';
Update `access_requirement` SET `comment`='Outland To Dark Portal' WHERE `id`='4352';
Update `access_requirement` SET `comment`='Dark Portal To Outland' WHERE `id`='4354';
Update `access_requirement` SET `comment`='The Underbog (Entrance)' WHERE `id`='4363';
Update `access_requirement` SET `comment`='The Steamvault (Entrance)' WHERE `id`='4364';
Update `access_requirement` SET `comment`='The Slave Pens (Entrance)' WHERE `id`='4365';
Update `access_requirement` SET `comment`='The Steamvault (Exit)' WHERE `id`='4366';
Update `access_requirement` SET `comment`='The Underbog (Exit)' WHERE `id`='4367';
Update `access_requirement` SET `comment`='The Slave Pens (Exit)' WHERE `id`='4379';
Update `access_requirement` SET `comment`='Sunstrider Isle to Eastern Plaguelands' WHERE `id`='4386';
Update `access_requirement` SET `comment`='Shadow Labyrinth (Exit)' WHERE `id`='4397';
Update `access_requirement` SET `comment`='Auchenai Crypts (Exit)' WHERE `id`='4399';
Update `access_requirement` SET `comment`='Mana Tombs (Exit)' WHERE `id`='4401';
Update `access_requirement` SET `comment`='Sethekk Halls (Exit)' WHERE `id`='4403';
Update `access_requirement` SET `comment`='Auchenai Crypts (Entrance)' WHERE `id`='4404';
Update `access_requirement` SET `comment`='Mana Tombs (Entrance)' WHERE `id`='4405';
Update `access_requirement` SET `comment`='Sethekk Halls (Entrance)' WHERE `id`='4406';
Update `access_requirement` SET `comment`='Shadow Labyrinth (Entrance)' WHERE `id`='4407';
Update `access_requirement` SET `comment`='Eastern Plaguelands To Sunstrider Isle' WHERE `id`='4409';
Update `access_requirement` SET `comment`='Serpentshrine Cavern (Entrance)' WHERE `id`='4416';
Update `access_requirement` SET `comment`='Karazhan, Main (Exit)' WHERE `id`='4436';
Update `access_requirement` SET `comment`='The Mechanar (Exit)' WHERE `id`='4455';
Update `access_requirement` SET `comment`='The Eye (Exit)' WHERE `id`='4457';
Update `access_requirement` SET `comment`='The Botanica (Exit)' WHERE `id`='4459';
Update `access_requirement` SET `comment`='The Arcatraz (Exit)' WHERE `id`='4461';
Update `access_requirement` SET `comment`='The Botanica (Entrance)' WHERE `id`='4467';
Update `access_requirement` SET `comment`='The Arcatraz (Entrance)' WHERE `id`='4468';
Update `access_requirement` SET `comment`='The Mechanar (Entrance)' WHERE `id`='4469';
Update `access_requirement` SET `comment`='The Eye (Entrance)' WHERE `id`='4470';
Update `access_requirement` SET `comment`='Battle Of Mount Hyjal (Exit)' WHERE `id`='4487';
Update `access_requirement` SET `comment`='Gruul\s Lair (Exit)' WHERE `id`='4534';
Update `access_requirement` SET `comment`='Gruul\s Lair (Entrance)' WHERE `id`='4535';
Update `access_requirement` SET `comment`='Black Temple (Entrance)' WHERE `id`='4598';
Update `access_requirement` SET `comment`='Black Temple (Exit)' WHERE `id`='4619';
Update `access_requirement` SET `comment`='Serpentshrine Cavern (Exit)' WHERE `id`='4418';
Update `access_requirement` SET `comment`='Socrethar\s Seat To Mainland' WHERE `id`='4523';
Update `access_requirement` SET `comment`='Zul\Aman (Entrance)' WHERE `id`='4738';
Update `access_requirement` SET `comment`='Zul\Aman (Exit)' WHERE `id`='4739';
Update `access_requirement` SET `comment`='Leap of Faith - End of fall' WHERE `id`='943';
Update `access_requirement` SET `comment`='Invasion Point, Cataclysm (Return Point)' WHERE `id`='4561';
Update `access_requirement` SET `comment`='Invasion Point, Cataclysm (Return Point)' WHERE `id`='4562';
Update `access_requirement` SET `comment`='Karazhan, Service (Entrance)' WHERE `id`='4135';
Update `access_requirement` SET `comment`='Magisters\ Terrace (Exit)' WHERE `id`='4885';
Update `access_requirement` SET `comment`='Magisters\ Terrace (Entrance)' WHERE `id`='4887';
Update `access_requirement` SET `comment`='Sunwell Plateau (Entrance)' WHERE `id`='4889';
Update `access_requirement` SET `comment`='Sunwell Plateau (Exit)' WHERE `id`='4891';
Update `access_requirement` SET `comment`='Utgarde Pinnacle (entrance)' WHERE `id`='4747';
Update `access_requirement` SET `comment`='Utgarde Pinnacle (exit)' WHERE `id`='4741';
Update `access_requirement` SET `comment`='The Nexus (entrance)' WHERE `id`='4983';
Update `access_requirement` SET `comment`='The Nexus (exit)' WHERE `id`='4981';
Update `access_requirement` SET `comment`='The Oculus (entrance)' WHERE `id`='5246';
Update `access_requirement` SET `comment`='Naxxramas (entrance1)' WHERE `id`='5191';
Update `access_requirement` SET `comment`='Naxxramas (entrance2)' WHERE `id`='5192';
Update `access_requirement` SET `comment`='Naxxramas (entrance3)' WHERE `id`='5193';
Update `access_requirement` SET `comment`='Naxxramas (entrance4)' WHERE `id`='5194';
Update `access_requirement` SET `comment`='Naxxramas (exit1)' WHERE `id`='5196';
Update `access_requirement` SET `comment`='Naxxramas (exit2)' WHERE `id`='5197';
Update `access_requirement` SET `comment`='Naxxramas (exit3)' WHERE `id`='5198';
Update `access_requirement` SET `comment`='Naxxramas (exit4)' WHERE `id`='5199';
Update `access_requirement` SET `comment`='Culling of Stratholme (entrance)' WHERE `id`='5150';
Update `access_requirement` SET `comment`='Culling of Stratholme (exit)' WHERE `id`='5148';
Update `access_requirement` SET `comment`='Violet Hold (entrance)' WHERE `id`='5209';
Update `access_requirement` SET `comment`='Violet Hold (exit)' WHERE `id`='5211';
Update `access_requirement` SET `comment`='Gundrak (entrance north)' WHERE `id`='5206';
Update `access_requirement` SET `comment`='Gundrak (entrance south)' WHERE `id`='5205';
Update `access_requirement` SET `comment`='Gundrak (exit north)' WHERE `id`='5277';
Update `access_requirement` SET `comment`='Gundrak (exit south)' WHERE `id`='5231';
Update `access_requirement` SET `comment`='Ulduar, Halls of Lightning (entrance)' WHERE `id`='5093';
Update `access_requirement` SET `comment`='Ulduar, Halls of Lightning (exit)' WHERE `id`='5091';
Update `access_requirement` SET `comment`='Ulduar, Halls of Stone (entrance)' WHERE `id`='5010';
Update `access_requirement` SET `comment`='Ulduar, Halls of Stone (exit)' WHERE `id`='5012';
Update `access_requirement` SET `comment`='Azjol-Nerub (entrance)' WHERE `id`='5117';
Update `access_requirement` SET `comment`='Azjol-Nerub (exit)' WHERE `id`='5115';
Update `access_requirement` SET `comment`='Azjol-Nerub (exit back)' WHERE `id`='5113';
Update `access_requirement` SET `comment`='Ahn\Kahet (entrance)' WHERE `id`='5215';
Update `access_requirement` SET `comment`='Ahn\Kahet (exit)' WHERE `id`='5213';
Update `access_requirement` SET `comment`='Chamber of Aspects, Obsidian Sanctum (entrance)' WHERE `id`='5243';
Update `access_requirement` SET `comment`='Chamber of Aspects, Obsidian Sanctum (exit)' WHERE `id`='5241';
Update `access_requirement` SET `comment`='Drak\Tharon Keep (entrance)' WHERE `id`='4998';
Update `access_requirement` SET `comment`='Drak\Tharon Keep (exit)' WHERE `id`='5000';
Update `access_requirement` SET `comment`='The Eye of Eternity (entrance)' WHERE `id`='5290';
Update `access_requirement` SET `comment`='The Oculus (exit)' WHERE `id`='5001';
Update `access_requirement` SET `comment`='Karazhan, Service (Exit)' WHERE `id`='4520';
Update `access_requirement` SET `comment`='Ulduar Raid entrance' WHERE `id`='5379';
Update `access_requirement` SET `comment`='Ulduar Raid exit' WHERE `id`='5381';
Update `access_requirement` SET `comment`='Vault of Archavon (Exit)' WHERE `id`='5262';
Update `access_requirement` SET `comment`='Vault of Archavon (Entrance)' WHERE `id`='5258';
Update `access_requirement` SET `comment`='Trial of the Champion' WHERE `id`='5505';
Update `access_requirement` SET `comment`='Trial of the Crusader' WHERE `id`='5503';
Update `access_requirement` SET `comment`='The Pit of Saron Portcullis' WHERE `id`='5637';
Update `access_requirement` SET `comment`='Forge of Souls Portcullis' WHERE `id`='5635';
Update `access_requirement` SET `comment`='The Halls of Reflection Gate' WHERE `id`='5636';
update `access_requirement` set `comment` ='IceCrown Citadel Spire (Exit)' where `id` ='5700';
update `access_requirement` set `comment` ='Culling of Stratholme (exit)' where `id` ='5181';
update `access_requirement` set `comment` ='Ahn\Kahet (exit)' where `id` ='5235';
update `access_requirement` set `comment` ='Gundrak - Exit 03' where `id` ='5276';
update `access_requirement` set `comment` ='Gundrak - Exit 01' where `id` ='5233';
update `access_requirement` set `comment` ='Dalaran Well teleporter' where `id` ='5273';
update `access_requirement` set `comment` ='The Gate Classic' where `id` ='5046';
update `access_requirement` set `comment` ='The Gate WoTLK' where `id` ='5047';
update `access_requirement` set `comment` ='DK 3 Floor to 2 Floor West' where `id` ='5017';
update `access_requirement` set `comment` ='DK 2 Floor to 3 Floor East' where `id` ='5029';
update `access_requirement` set `comment` ='Eversong Woods, Duskwither Spire, Orb high' where `id` ='4267';
update `access_requirement` set `comment` ='Ghostlands, duskwither spire, balcony' where `id` ='4233';
update `access_requirement` set `comment` ='Scholomance - Out' where `id` ='2547';
update `access_requirement` set `comment` ='Scholomance - Out' where `id` ='2548';
update `access_requirement` set `comment` ='Scholomance - Out' where `id` ='2549';
update `access_requirement` set `comment` ='The Botanica - The Mechanar' where `id` ='4612';
update `access_requirement` set `comment` ='The Mechanar - The Botanica' where `id` ='4614';
update `access_requirement` set `comment` ='Ashenvale - Silverwing Grove (Warsong Gulch - Alliance Entrance)' where `id` ='3650';
update `access_requirement` set `comment` ='Barrens - Mor\shan Base Camp (Warsong Gulch - Horde Entrance)' where `id` ='3654';
update `access_requirement` set `comment` ='Arathi Basin Horde In' where `id` ='3954';
update `access_requirement` set `comment` ='Arathi Basin Alliance In' where `id` ='3953';
update `access_requirement` set `comment` ='Trial of the Champion (exit)' where `id` ='5510';
update `access_requirement` set `comment` ='Trial of the Crusader (exit)' where `id` ='5508';
update `access_requirement` set `comment` ='Ulduar (Gallery)' where `id` ='5390';
update `access_requirement` set `comment` ='q12019: floor1 before quest done' where `id` ='5332';
update `access_requirement` set `comment` ='q12019: floor2 before quest done' where `id` ='5340';
update `access_requirement` set `comment` ='q12019: floor2 after quest done' where `id` ='5338';
update `access_requirement` set `comment` ='q12019: floor1 after quest done' where `id` ='5334';
update `access_requirement` set `comment` ='q12710: floor1' where `id` ='5051';
update `access_requirement` set `comment` ='q12710: floor2' where `id` ='5079';
update `access_requirement` set `comment` ='q12710: floor1' where `id` ='5080';
update `access_requirement` set `comment` ='q12710: ground' where `id` ='5061';
update `access_requirement` set `comment` ='Halls of Reflection (Exit)' where `id` ='5646';
update `access_requirement` set `comment` ='Forge of Souls (Exit) Pit of Saron (Entrance)' where `id` ='5688';
update `access_requirement` set `comment` ='Forge of Souls (Exit)' where `id` ='5642';
update `access_requirement` set `comment` ='IceCrown Citadel (Exit)' where `id` ='5668';
update `access_requirement` set `comment` ='IceCrown Citadel (Entrance)' where `id` ='5670';
update `access_requirement` set `comment` ='Pit of Saron (Exit)' where `id` ='5643';
update `access_requirement` set `comment` ='Pit of Saron (Exit) Halls of Reflection (Entrance)' where `id` ='5683';
update `access_requirement` set `comment` ='IceCrown Citadel Spire (Entrance)' where `id` ='5698';
update `access_requirement` set `comment` ='Ulduar (Planetarium)' where `id` ='5433';
update `access_requirement` set `comment` ='Ulduar (tram)' where `id` ='5402';
update `access_requirement` set `comment` ='Ulduar (tram)' where `id` ='5432';